def new_prefunded_account(address, private_key):
    return struct(address=address, private_key=private_key)


# This information was generated by:
#  1) https://iancoleman.io/bip39/
#  2) Enter the mnemonic (unless you use the default)
#  3) Copying the pubkey/priv key outputted information
PRE_FUNDED_ACCOUNTS = []
